### ISSUE TITLE
accessibility layer is called multiple times  

### ISSUE THREAD

**Issue by RELNO** [CityScope/CSL_Hamburg_Grasbrook#101]
<img width="828" alt="Screen Shot 2020-01-06 at 16 57 28" src="https://user-images.githubusercontent.com/14296774/71852112-f9fbfe80-30a5-11ea-865c-04aaf77786ff.png">

If this is only prompting for layer data already fetched, discard this issue. Otherwise, this is a triple call for same layer.

**Comment by andredaa** [comment]
fixed with https://github.com/CityScope/CSL_Hamburg_Grasbrook/pull/108
