### ISSUE TITLE
Add multiple basemap sources

### ISSUE THREAD

**Issue by RELNO** [CityScope/CSL_Hamburg_Grasbrook#11]
@yasushisakai how should multiple sources be added here: 
https://github.com/CityScope/CSL_Hamburg_Grasbrook/blob/a40485191cc042d05bd5ad9d2d4ca40cc3dc2206/src/app/basemap/moduleDataToMapHandler/module-data-to-map-handler.service.ts#L12

**Comment by yasushisakai** [comment]
I was thinking to have a function for layers and data sources separately, since I can't guarantee layers always has a dynamic data source. 

One question is will a service always hold a single layer and a datasources? (I see MoCho having multiple endpoints...)

**Comment by RELNO** [comment]
> I was thinking to have a function for layers and data sources separately

Let's try that 

> will a service always hold a single layer and a datasources

No -> one simple example is a module that  gets non-geo-refed data. In this case, the module will have to call cityIO service in order to match its own data to the georef coming from cityIO.
