### ISSUE TITLE
Add a GAMA module

### ISSUE THREAD

**Issue by agrignard** [CityScope/CSL_Hamburg_Grasbrook#12]
Some exampel of file sent by GAMA has been produced recently.

It is ready to be "seen and visualized" by the frontend.

As discusssed with @RELNO and @yasushisakai a module called gama has to be created here
https://github.com/CityScope/CSL_Hamburg_Grasbrook/tree/master/src/app/basemap

**Comment by RELNO** [comment]
great -- please see https://github.com/CityScope/CSL_Hamburg_Grasbrook/tree/template-module-listerner/src/app/basemap/testHeatmap 
this is a generic imlementation of cityIO module listerener, that can be adopted to GAMA

**Comment by agrignard** [comment]
Ok so let's consider it as closed then

**Comment by agrignard** [comment]
I guess the structure has changed this last days.

Where is the equivalent of this module now?
https://github.com/CityScope/CSL_Hamburg_Grasbrook/tree/template-module-listerner/src/app/basemap/testHeatmap

**Comment by agrignard** [comment]
Ok it's here
https://github.com/CityScope/CSL_Hamburg_Grasbrook/tree/master/src/app/basemap/moduleDataToMapHandler/testHeatmap

In any case I will create a Gama module as the way to display this layer is not as generic as a heatmap (it doesn't have to be a heatmap, it can be many other thing that need to be configured)

**Comment by agrignard** [comment]
@RELNO what is the proper way to test this kind of module? Right now when I run the project I get the map of the site, but how can I test and visualize some of the modules? I guess it's happening in basemap.component.ts this is where I should add my layer right?

**Comment by RELNO** [comment]
> but how can I test and visualize some of the modules?

@yasushisakai and I currently work on this, this is not 100% done yet. For now https://github.com/CityScope/CSL_Hamburg_Grasbrook/commit/e777529a02134afdccbf8840d0b2ebdf8e1f0948 has working example for only the cityIO grid. But we're not final yet on the most efficient way to do multiple `GET` req for each module. This is what we're dealing with in https://github.com/CityScope/CSL_Hamburg_Grasbrook/issues/18.

**Comment by agrignard** [comment]
Ok so the bridge is now made between cityIO/grassbrook and GAMA with this model

https://github.com/CityScope/CS_Simulation_GAMA/blob/master/CS_CityScope_GAMA/models/MicroSimulationFromMacroMobilityModel.gaml

So here is a file that has been produced by GAMA (for now a toy model that just send trajectory of agents)

@RELNO I let you look if this simple example work for you, we will then see how to have the model running on a server to be ready to update at any change.

**Comment by RELNO** [comment]
@agrignard thanks -- looking into the data, there are 2 issues:

```
{
	"segments": [
		[10.009245822037602, 53.51982688689586, 0.0],
		[10.023941513504456, 53.53480909649631, 0.0]
	],
	"vendor": 1
},
```
- there is no time difference between point A to point B
- there is only one segment in each trip for each vendor

**Comment by agrignard** [comment]
Yes it was a light push. I just put a bigger one

**Comment by RELNO** [comment]
@agrignard layer went back to use `vendor` and we still have the initial all-agents pulse issue.

**Comment by agrignard** [comment]
Do you check this url ?
https://cityio.media.mit.edu/api/table/grasbrook/cityIO_Gama_Hamburg

**Comment by agrignard** [comment]
First bet aversion is consider as done here:
https://cityio.media.mit.edu/api/table/grasbrook/cityIO_Gama_Hamburg

With this commit
https://github.com/CityScope/CS_Simulation_GAMA/commit/193e852f3d803048b0b67600c5a7e09c4e31e6fd

I close this issue for now and we migth open some more specific ones related to the model itself and to the multi user part
