### ISSUE TITLE
Basemap dependant on Cityio

### ISSUE THREAD

**Issue by yasushisakai** [CityScope/CSL_Hamburg_Grasbrook#14]
**I recall @RELNO pointing this out**

Basemap needs to depend on `cityio` in order to perform
`initializeMap(cityIOdata)` which looks like it is a different level than
other simulations/API calls.

yet, from the last conversation, `cityIOdata` updates every n seconds, and the `ModuleDataToMapHandler` is responsible to push new updates...

**Comment by RELNO** [comment]
we can split -- 
1. One early call to cityIO for table init -> as a standalone GET req. 
2. Periodic Service that gets cityIO updates. 
It's a bit of double code, but might worth it since we don't mix and match. A service stays a service, an init call is just a one time event. Thoughts?

**Comment by yasushisakai** [comment]
yes, I agree (I guess it adds more code but easier to understand)

**Comment by RELNO** [comment]
closing as #18 should address this
