### ISSUE TITLE
newer angular has vulnerabilities

### ISSUE THREAD

**Issue by yasushisakai** [CityScope/CSL_Hamburg_Grasbrook#20]
https://github.com/angular/angular-cli/issues/14138
😢 

@RELNO that was a global thing

**Comment by yasushisakai** [comment]
my mac and win have same warnings. don't update `@angular/cli`

**Comment by RELNO** [comment]
thanks for the heads up -- which is the last stable build?

**Comment by yasushisakai** [comment]
closing from @janbehrens advice
this was not the cause of not compiling.
