### ISSUE TITLE
Bounds of the Physical table

### ISSUE THREAD

**Issue by agrignard** [CityScope/CSL_Hamburg_Grasbrook#21]
In order to run any backend model (abm,energy, noise, etc)  the boundary of the studied area is needed to contextualized and spacialized the model.

Ideally a .shp or a geojson file representing the boundary of the table would be very useful. (e.g https://github.com/CityScope/CS_Simulation_GAMA/blob/master/CS_CityScope_GAMA/includes/City/volpe/table_bounds.shp).

**Comment by RELNO** [comment]
can we continue this in https://github.com/CityScope/CSL_Hamburg_Grasbrook/issues/9? 
Look for the first comment, there's a Qgis link to the map.

**Comment by agrignard** [comment]
OK what about pushing this .shp in the github?
