### ISSUE TITLE
Update layer using  `.setData(source)`

### ISSUE THREAD

**Issue by RELNO** [CityScope/CSL_Hamburg_Grasbrook#22]
considering the `config.json` approach for creating a new layer, where should regular API updating happens using MB native:`.setData(url);`? (following this [method](https://docs.mapbox.com/mapbox-gl-js/example/live-geojson/))

**Comment by illsio** [comment]
I will push an example tomorrow. So far I suggest setData to happen in the basemap component. If these kind of layer features get more advanced it should get outsourced.

**Comment by RELNO** [comment]
Thanks -- @yasushisakai is also looking into this, with an attempt to outsource this resources update into `moduleDataToMapHandler` (https://github.com/CityScope/CSL_Hamburg_Grasbrook/issues/18). Though we're not certain if it's the right way to do it.

**Comment by illsio** [comment]
My suggestion is included in branch layer-loading-and-inteval-update

**Comment by RELNO** [comment]
@illsio thanks, clear logic. I failed trying to make it work even with a simpler API call than cityIO, I saw it's still under 'to do'
