### ISSUE TITLE
can't compile

### ISSUE THREAD

**Issue by yasushisakai** [CityScope/CSL_Hamburg_Grasbrook#23]
dumping stdout and stderr.
node, npm and ng versions are same as @RELNO 

I've done `npm audit` and `npm audit fix` and followed instructions but does not resolve.(related to #20)

```shell
node --version
v10.15.1

npm --version
6.9.0

ng --version (outside repo)

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 7.3.3
Node: 10.15.1
OS: darwin x64
Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.13.3
@angular-devkit/core         7.3.3
@angular-devkit/schematics   7.3.3
@schematics/angular          7.3.3
@schematics/update           0.13.3
rxjs                         6.3.3
typescript                   3.2.4
    

npm install
npm WARN bootstrap@4.3.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.3.1 requires a peer of popper.js@^1.14.7 but none is installed. You must install peer dependencies yourself.

audited 42690 packages in 4.377s
found 5 high severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details

ng serve
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **

Date: 2019-04-15T21:40:43.171Z
Hash: fe04d38885e92ed92ad7
Time: 6763ms
chunk {es2015-polyfills} es2015-polyfills.js, es2015-polyfills.js.map (es2015-polyfills) 284 kB [initial] [rendered]
chunk {main} main.js, main.js.map (main) 1.87 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 93.1 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.08 kB [entry] [rendered]
chunk {scripts} scripts.js, scripts.js.map (scripts) 78.2 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 1.05 MB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 327 kB [initial] [rendered]

ERROR in src/app/basemap/moduleDataToMapHandler/grid/grid-three/grid-three.service.ts(31,28): error TS2339: Property 'MercatorCoordinate' does not exist on type 'typeof mapboxgl'.
src/app/basemap/moduleDataToMapHandler/grid/grid-three/grid-three.service.ts(35,28): error TS2339: Property 'MercatorCoordinate' does not exist on type 'typeof mapboxgl'.
src/app/basemap/moduleDataToMapHandler/grid/grid-three/grid-three.service.ts(39,28): error TS2339: Property 'MercatorCoordinate' does not exist on type 'typeof mapboxgl'.

[34mℹ[39m [90m｢wdm｣[39m: Failed to compile.
```

**Comment by RELNO** [comment]
Would it compile if you skip the grid-three loading? Also, please clarify this is an Ubuntu issue (for now..)

**Comment by janbehrens** [comment]
I've encountered the same error. Looks like no type definitions for mapboxgl are available.
As a temporary workaround you can cast it to 'any' by replacing `mapboxgl` with `(<any>mapboxgl)`.

**Comment by janbehrens** [comment]
... and don't worry about the npm audit warnings. They appear frequently. Just make sure you check for new major of your packages every now and then.

**Comment by yshimbo** [comment]
I've encounter same issue on Windows10 64bit.

Please check L16 & 17 in grid-three.service.ts.
Sequence is not correct. Try to swap L16 & 17.
(See API reference of mapgl: https://docs.mapbox.com/mapbox-gl-js/api/#mercatorcoordinate.fromlnglat)

Unfortunately, type definition error still remained...

**Comment by yshimbo** [comment]
I've encounter same issue on Windows10 64bit.

I've encountered same issue on Windows10 64bit.

After failing, I try to update grid-three.service.ts.(Just swapped L16 and L17.)
Then compile process succeeded.
But restarting the process (ng serve), compile failed once again...

Unfortunately, type definition error still remained...

**Comment by yasushisakai** [comment]
@janbehrens thanks for the tip I will come back when tested, I will probably do a PR for this.

**Comment by RELNO** [comment]
> After failing, I try to update grid-three.service.ts.(Just swapped L16 and L17.)

@illsio do you refer to:
``` 
 var modelOrigin = [
      cityiodata.header.spatial.latitude,
      cityiodata.header.spatial.longitude
    ];
```
?

**Comment by yshimbo** [comment]
@RELNO
Yes.
But I think swapping those lines is not a problem.
The sequence what I did is 
ng serve  -> compile failed -> modify 'grid-three.service.ts' -> compile success -> terminate 'ng serve' process -> ng serve (once again) -> compile failed.


-Reason of swapping the lines.
As far as reading mapbox reference, the sequence of parameters of MercatorCoordinatefromLngLat is {lng, lat}.

**Comment by RELNO** [comment]
@yshimbo thanks for the in sight, I'll follow this format.

**Comment by RELNO** [comment]
Closing for now per @janbehrens solution.
