### ISSUE TITLE
merge cityio.service & grid-layer.service 

### ISSUE THREAD

**Issue by RELNO** [CityScope/CSL_Hamburg_Grasbrook#30]
For now, `cityio.service` + `grid-layer.service` both implement api calls, which is redundant.
cityio service should be as generic as possible and `grid-layer.service` could be [maybe] consolidated into grid.layer.ts

**Comment by yasushisakai** [comment]
so naming. Should it be `grid-layer.service` or `cityio.service` ... can I decide?

**Comment by RELNO** [comment]
https://gph.is/2eAGJWk

**Comment by RELNO** [comment]
done @https://github.com/CityScope/CSL_Hamburg_Grasbrook/commit/6a68ced70762d502d617c8fca098da0d6d9eb8b7
