### ISSUE TITLE
CORS Header Exception

### ISSUE THREAD

**Issue by illsio** [CityScope/CSL_Hamburg_Grasbrook#33]
I get a CORS header exception for a request to (cityio.service.ts)
https://cityio.media.mit.edu/api/table/virtual_table
as well as 
https://cityio.media.mit.edu/api/table/abm_service_Hamburg
I did not get this exception this morning.
#32 therefore does not run outside of the MediaLab

**Comment by RELNO** [comment]
@illsio looks like cityIO is dead -- @yasushisakai can you take a look?

**Comment by RELNO** [comment]
closing and moving to cityIO
