### ISSUE TITLE
GeoJSON Grid?

### ISSUE THREAD

**Issue by illsio** [CityScope/CSL_Hamburg_Grasbrook#35]
As I was looking into the grid.layer.ts and I was thinking about future interaction with the grid. How I understand the Grasbrook project, there will be a tablet version in which the interaction is without a CityScope table. So I imagine interaction will happen by clicking on a 3d grid objects. For me that interaction would be a lot easier to code if the grid would not be drawn by Three but would be a Geo-JSON instead. Having the grid as a Geo-JSON would also have the advantage of it being georeferenced for potential simulations, it would be exportable and easy to reproduce on different mapping clients, it could be easier to include potential existing Grasbrook designs and it could be configured via the config.json.
I am aware that we had this discussion before. I personally do not see advantages of a Three-Grid - but I might be easy to convince =)
Please excuse my poor hand draw grid: https://jsfiddle.net/Lbkz26sd/

**Comment by andredaa** [comment]
Would it also make it easier to put a georeferenced result layer on top? The noise-tool currently exports geojson. 
How did you do when projecting your results from the GAMA analysis etc?

**Comment by RELNO** [comment]
@illsio -- thanks for the input  -- https://jsfiddle.net/Lbkz26sd/ is funny ;)

 Yes, geojson if far more ideal for this for many different reasons including UI and performance. 
We've tested it before and faced some geo-projection issues. However, it seems that @andredaa  solved it with a module that well converts cityIO grid to geojson on the fly. When he's done building it, we can replace the grid with geojson.

**Comment by RELNO** [comment]
closing following merge @ https://github.com/CityScope/CSL_Hamburg_Grasbrook/commit/411ece596f679e6046e60e2a18c580ccae548794
