### ISSUE TITLE
Basic login window in home.component

### ISSUE THREAD

**Issue by RELNO** [CityScope/CSL_Hamburg_Grasbrook#39]
compose a minimal user/p-w login window in `home.component`
The comp. will send a hashed version of the login detail (computed at end-user machine) to cityIO which - if OKed -> will return a hash ID of specific user (i.e arch-office-1)

**Comment by illsio** [comment]
See recent commit in branch 'basic_auth'.
So far the fake-backend.ts will provide user authentification.
The jwt.interceptor will set the authentification header.
Waiting for #40 for further frontend development.

**Comment by RELNO** [comment]
@illsio looks good thanks --  in terms of UX, I was imagining the following sequence:

1. User land on `home`  (nice GB splash screen :))
2. user has login options OR `view CityScope table` option 
3. If login => go to map with interaction abilities (i.e - click on cells and edit properties)
4. if `view CityScope table` => go to map WITHOUT editing features, only viewing what is read from the tangible table. click on cell only show it's meta, but no editing.

What do you think?

**Comment by illsio** [comment]
- Changed CSS to SCSS
- Simple Splash (please edit design)
- Logged in users can edit grid height
     Click on grid -> height = height+5 (to a max of 50)
     Ctrl + click on grid -> height = height-5

**Comment by RELNO** [comment]
Great job, thanks. I've pushed a few CSS splash screen edits, and added a multi-select & edit for grid cells (using 'w' to change height). I'll merge and we'll start a new pull for UI and log-in.
