### ISSUE TITLE
Hiding all MapBox Buildings on GB

### ISSUE THREAD

**Issue by illsio** [CityScope/CSL_Hamburg_Grasbrook#43]
We have to hide all buildings on the Grasbrook - otherwise the overlap with our 3d-grid.
The mapbox buldings do not have unique IDs. @RELNO maybe you can somehow either filter your mapboy style or add unique properties to the corresponding buildings on GB. If the buildings would be identifiable via a property I should be able to render them invisible.

**Comment by RELNO** [comment]
added as separated layer with toggle in https://github.com/CityScope/CSL_Hamburg_Grasbrook/commit/a8e2f68123afa7c3e8a8c2a9037b973d878a2b5d
