### ISSUE TITLE
cannot select new grid cells after using layer toggle

### ISSUE THREAD

**Issue by RELNO** [CityScope/CSL_Hamburg_Grasbrook#44]
in https://github.com/CityScope/CSL_Hamburg_Grasbrook/commit/a8e2f68123afa7c3e8a8c2a9037b973d878a2b5d, after toggling the grid layer via menu, user cannot anymore select new cells.

**Comment by illsio** [comment]
done?

**Comment by RELNO** [comment]
Almost, still not working for on/off `geojosn-grid` layer

**Comment by illsio** [comment]
https://github.com/CityScope/CSL_Hamburg_Grasbrook/commit/35af4fbffadda17fc330c34522f922398d5e6e49 was pushed to basic_auth - I dont think it has made its way to master. I cant replicate the issue anymore on 'basic_auth' branch.

**Comment by RELNO** [comment]
I think this issue is indeed gone, but now I'm seeing that 'map' and 'login' modes are the same: if a user is logged and go to map, they still can edit the map. Desired functionality is 'map' only show CS tangible table and login only shows user

**Comment by illsio** [comment]
Sorry I don't get it - the functionality from #39 is still the same on 'basic_auth' branch

**Comment by RELNO** [comment]
> Sorry I don't get it - the functionality from #39 is still the same on 'basic_auth' branch


I'll close this and start another issue as I'm working on a different branch now.
