### ISSUE TITLE
Add full site grid in geojson 

### ISSUE THREAD

**Issue by RELNO** [CityScope/CSL_Hamburg_Grasbrook#47]
@andredaa please create a full site grid in geojson based on the extents here: https://github.com/CityScope/CSL_Hamburg_Grasbrook/blob/local-cityio/README.md

**Comment by andredaa** [comment]
alright. how many columns and rows are there?

https://cityio.media.mit.edu/api/table/grasbrook/
Spatial information still reads 10 rows and 10 columns

**Comment by andredaa** [comment]
Given the coordinates of the table extends in the readme - it should be roughly 44rows and 78 cells.

**Comment by RELNO** [comment]
> https://cityio.media.mit.edu/api/table/grasbrook/
Spatial information still reads 10 rows and 10 columns 

this is still the old CS table in the lab. I will create a separate endpoint for it today. As for the grid dims, we use 16^2m cells, so It's around the numbers you mentioned, but please double check

**Comment by andredaa** [comment]
OK, thank you!
Could you please also double check the table rotation? The old one is 325° - which seems a few degrees off for the coordinates given as table-extends

**Comment by andredaa** [comment]
Here a geojson for the entire project site: https://github.com/andredaa/city_io_to_geojson/blob/master/resulting_jsons/geojson_EPSG:4326.json

- no cell margins yet
- table rotation updated to 326°

This is an adaptation of the software, so that it will only be used **once** during table initialisation.
The software provides a grid with the correct geolocation of each cell in the desired coordinate reference system.
Changes:

    table specifications are read from config instead of cityIO
    resulting geojson spawns over entire project site
    cells no longer have properties like color, height and type

Cell properties would be set by the front end - possibly using cell_id

**Comment by RELNO** [comment]
thanks -- we do actually want to initiate the grid with some height, type and color values so that we can right away update these with values coming in from the cityIO. 

<img width="694" alt="Screen Shot 2019-07-17 at 11 04 50" src="https://user-images.githubusercontent.com/14296774/61386707-c2449480-a882-11e9-9f53-f6d55889cfc4.png">

**Comment by andredaa** [comment]
we discussed this differently here
https://github.com/andredaa/city_io_to_geojson/issues/2#issuecomment-505792404

I could read the properties once from an endpoint of the table. However this feels a bit pointless, as the information on the properties will be overwritten soon. The purpose of the geojson created is rather to provide geolocations for each cell.

**Comment by andredaa** [comment]
on a different note: geojson.io draws the lines somewhat curvy. (your screenshot)
In QGIS the lines look perfect. 
![grafik](https://user-images.githubusercontent.com/4631906/61390835-ce007d00-a8bb-11e9-9168-af865d5ba1c3.png)

**Comment by RELNO** [comment]
> we discussed this differently here
andredaa/city_io_to_geojson#2 (comment)
I could read the properties once from an endpoint of the table. However this feels a bit pointless, as the information on the properties will be overwritten soon. The purpose of the geojson created is rather to provide geolocations for each cell.

we do not need to read the cell features from cityIO on init. What we need is to create the static geojson grid with zeroed/nulled/random init parms. In other words, create each grid cell with empty Nulled fields for hight, type, color etc. Make sense?

**Comment by andredaa** [comment]
So - the geojson gets created based on table specs , specified in a config file now. No connection to endpoint. 

I think the properties could be added in front-end - as it handles the updating and display of the grid - and as there might be future properties we don't yet know about. 

But I agree that this way will probably it keep the front-end code nice and slim. 

So I set nulled properties now. Cell rotation is equal to table rotation.

Example resulting json:
https://github.com/andredaa/city_io_to_geojson/blob/master/resulting_jsons/geojson_EPSG:4326.json

**Comment by RELNO** [comment]
thanks -- can you look into the dims of each cell? It appears they are close but not exactly 16x16: 
<img width="258" alt="Screen Shot 2019-07-17 at 12 41 29" src="https://user-images.githubusercontent.com/14296774/61394042-4fdab100-a890-11e9-99de-db091bdedf76.png">

**Comment by andredaa** [comment]
I will do tomorrow.

**Comment by andredaa** [comment]
I used the python shapely module to calculate the cells' area of the metric projection: 255.999997 
It looks like it's due to webmarcator not repecting area: (see this dicussion : https://stackoverflow.com/questions/51554602/how-do-i-get-the-area-of-a-geojson-polygon-with-python  )

> Because Web Mercator doesn't preserve area: geography.hunter.cuny.edu/~jochen/GTECH361/lectures/lecture04/…. Welcome to map projections. Your question is a better for Geographic Information Systems (There's nothing wrong with your code, just your choice of projection.) and is better off being specific about getting the wrong value for the area. And here's a link to the actual 3857 projection; the one you link is something else

For calculating the area in Python or QGIS all forums suggest to go convert to metric projection before calculating. Then the areas are true.

**Comment by RELNO** [comment]
@andredaa ok great. Can you share the most updated grid geojson?

**Comment by andredaa** [comment]
https://github.com/andredaa/city_io_to_geojson/blob/master/resulting_jsons/geojson_EPSG:4326.json

**Comment by RELNO** [comment]
merging with https://github.com/CityScope/CSL_Hamburg_Grasbrook/issues/55#issuecomment-516427287
