### ISSUE TITLE
Create test user with POST and GET functionality 

### ISSUE THREAD

**Issue by RELNO** [CityScope/CSL_Hamburg_Grasbrook#48]
We would want to test with one user that has proper credentials with which they can:
- `GET` cityio data for their own endpoint (e.g `https://cityio.media.mit.edu/api/table/le_corbusier/`)
- 'POST' edits to the grid into the same endpoint 

**Next step** will be module with super-user access to analyze `le_corbusier` output

**Comment by illsio** [comment]
@RELNO is it still the plan to have an endpoint for every user?
@yasushisakai this endpoint should be accessible by elmo?

**Comment by RELNO** [comment]
@illsio I'm not sure. From clearity point of view, having all within `.../api/table/grasbrook` make sense. However, we only designed 1 level field depth (`grasbook/__level0__`) so having multiple endpoints might mess the this (i.e, `noise_office_0`, `noise_office_1`..) 
What do you think?

**Comment by illsio** [comment]
One Endpoint is enough. CityIO should give users individual auth tokens and therefor know who is requesting. It makes different endpoints obsolete.

**Comment by illsio** [comment]
cityIOs response to a login is a user-specific token. therefor if a request to cityIO is made by a user, cityIO can look up the user and forward the request to noise, abm, etc.
user specific endpoints are in strong contrast to DRY principles.
![grafik](https://user-images.githubusercontent.com/36763878/62603456-3c9e8c80-b8f6-11e9-815d-6566df1e28e3.png)

**Comment by RELNO** [comment]
It make sense -- so to clarify: `grasbrook/noise` will only have one result at a time, pointing to the last token sent to it by cityIO?

**Comment by illsio** [comment]
grasbrook/noise can hold as many results at the time as necessary - one for each user, the users noise model history. I am only aiming at: Anything that happens behind noise_office_0 can happen by querying the grasbrook/noise with the users token.

**Comment by RELNO** [comment]
> grasbrook/noise can hold as many results at the time as necessary - one for each user, the users noise model history. 

So do you see `grasbrook/noise` having `grasbrook/noise/_office_1_/`, `grasbrook/noise/_office_2_/`? I'm asking because currently, cityIO is designed to only go 1 level deeper (i.e  `grasbrook/noise`). @yasushisakai can you weigh in on this?

**Comment by illsio** [comment]
I still do not see the necessity for office/user specific endpoint, since user request are identifiable via their token.

**Comment by RELNO** [comment]
> I still do not see the necessity for office/user specific endpoint, since user request are identifiable via their token.


Let's see if I get it: when a user make a change, they submit their cityIO req. along with their token. 
Then, module (let's say noise) gets this change via its listener and compute a response.  When it's done, it posts back to cityIO with the same token. Then the end-user can grab the result by searching cityIO database for response with the same token. 

Is that the idea?

**Comment by illsio** [comment]
Yes - that is how I would imagine this process.

**Comment by RELNO** [comment]
ok -- I guess it's a question to @yasushisakai as to how can we store and re-store responses in the cityio database, and pulled them by the user with the right token.

**Comment by RELNO** [comment]
I believe this is does now, @luftj @illsio ?

**Comment by illsio** [comment]
I believe it is
