### ISSUE TITLE
Add sidebar editing for one cell/multicell params 

### ISSUE THREAD

**Issue by RELNO** [CityScope/CSL_Hamburg_Grasbrook#52]
After selection of one or many cells (as  #51 describes), a sidebar editing mode should pop, allowing for metadata edits. https://material.angular.io/components/select/overview is a starting point. The input should probably be of sliders: 
![image](https://user-images.githubusercontent.com/14296774/61318080-3bd07a00-a7d2-11e9-9916-b30a70198c75.png)

A moveable bar is also an option: https://material.angular.io/cdk/drag-drop/overview#customizing-the-drag-area-using-a-handle

**Comment by illsio** [comment]
please check out the branch ...
we can add new parameters to the menu later.
if this is sufficient for now, please merge into master

**Comment by RELNO** [comment]
looks like this is done in https://github.com/CityScope/CSL_Hamburg_Grasbrook/commit/e0c78b50d4387e442dcfdd2d5d6b576bd05ef11d
