### ISSUE TITLE
Grid localstorage

### ISSUE THREAD

**Issue by RELNO** [CityScope/CSL_Hamburg_Grasbrook#54]
Should grid remines in `localstorage` and if so when: 

-> differences for observatory and logged in modes 
-> if user closes via 'x' and chooses not save - should we delete localstorage as well?!

**Comment by illsio** [comment]
done? please merge if desired functionality is included.

**Comment by illsio** [comment]
The same branch should resolve #56 as well

**Comment by RELNO** [comment]
Looks good -- at times, deselection only results with black colors (for non-black types). Any idea?

**Comment by illsio** [comment]
Sorry - I cannot replicate that.
I selected and deselected the full grid twice and everything is back to the initial color.

**Comment by RELNO** [comment]
Cannot as well again -- I think it had to do with local cache upon pulling. closing -- please pull and I'll merge
