### ISSUE TITLE
Pull all layer on init from local 

### ISSUE THREAD

**Issue by RELNO** [CityScope/CSL_Hamburg_Grasbrook#55]
`src/assets/modules_json_backup` holds a `json` copy for each layer, grid and module. 
On init, read from these layers to have a quick visual of layers while fetching from cityio.
Then, if any module is offline, default to this placeholder.

**Comment by illsio** [comment]
https://github.com/CityScope/CSL_Hamburg_Grasbrook/commit/691b03f9f48b682913064d4e20188254a0f7af79

**Comment by RELNO** [comment]
@illsio yes, that's the placeholder. Still need to implement the logic to default to them at init / or when no cityio data is in place

**Comment by illsio** [comment]
I would suggest to only load the default layers when cityIO is not available.
The potential double loading of layers will probably not look good if the layers get loaded regardless of cityIO beeing online. I suggest that every layer defined in the config.json gets an additional attribute like 'backup-layer'.

**Comment by RELNO** [comment]
Agreed - the backup layer parameter sounds like a good idea

**Comment by RELNO** [comment]
Can you please provide a boilerplate example of how you'd load one of these stale json/geojson layers on init (similar to what you did with the deck layer?) -- What we'd like to eventually have is an empty/clean GEOjson grid loading at init from local or remote json. Loading it through config is easy enough, but how would you load it in a way that later allows us to edit its parameters?

**Comment by illsio** [comment]
I have encountered problems with the grid access.
If I load the grid from the assets folder, it is not editable (same grid a the one i request from cityIO).
This might be a problem we cannot solve - mapboxGL might treat data in local files different than requested data.

**Comment by RELNO** [comment]
Is serving it locally different from the grid we read now from the config.json file?

**Comment by illsio** [comment]
Weirdly mapboxgl treats these different.

**Comment by RELNO** [comment]
Might be a load issue of the json file? Should it be .geojson insead?

**Comment by illsio** [comment]
Please see branch https://github.com/CityScope/CSL_Hamburg_Grasbrook/tree/local_json_sources and try selecting cells

**Comment by RELNO** [comment]
could not select cells: 
<img width="541" alt="Screen Shot 2019-08-21 at 09 11 39" src="https://user-images.githubusercontent.com/14296774/63434759-b3a64b80-c3f3-11e9-81b4-5d0e3cfd0170.png">

In any case, can you compare this branch to https://github.com/CityScope/CSL_Hamburg_Grasbrook/pull/69 and conslidate into the PR?

**Comment by RELNO** [comment]
Closing due to current design.
