### ISSUE TITLE
Roads network and Spatial data consolidation

### ISSUE THREAD

**Issue by agrignard** [CityScope/CSL_Hamburg_Grasbrook#66]
Right now there is a file describing the site data but it is pretty hard computationally to use as it is
https://github.com/CityScope/CSL_Hamburg_Grasbrook/blob/master/src/assets/site%20data/grasbrook_shape_and_roads.json

But it is not usable as it is for a different reason:

0. format is json intead of geojson (it is a geojson structure)
1. There is no projection defined  ("crs": { "type": "name", "properties": { "name": "epsg:4326" } }) 
2. There is a mix of polygon and polyline in the same file.

@andredaa Do we know where this data came from? Can we modify it or do we need to be compatible with this format? 

There is also some other data that might be useful here maybe we should think about consolidating the database in a common place
https://github.com/CityScope/CS_Mobility_Service/tree/master/scripts/cities/Hamburg/clean

**Comment by RELNO** [comment]
looks like we've converged on a more detailed baseline roads geojson for ABM & mobility service modules, closing this for now.
