### ISSUE TITLE
maptastic not working on linux

### ISSUE THREAD

**Issue by andredaa** [CityScope/CSL_Hamburg_Grasbrook#74]
@luftj : i had to rename all instances of "Maptastic" into "maptastic" in the maptastic.js and maptastic.min.js ---> these changes probably would not survive a "npm install" if installed on a new machine.
i hope there is a better version of making this work.

**Comment by RELNO** [comment]
@andredaa please review this: https://stackoverflow.com/questions/8481488/is-git-not-case-sensitive
It's not good practice to lowercase class name. Try to see if git lowercase commit is the issue. thanks.

**Comment by luftj** [comment]
But it's coming from npm, not git. We don't commit any maptastic files.

**Comment by luftj** [comment]
`ERROR in ./node_modules/maptastic/dist/maptastic.min.js
Module not found: Error: Can't resolve 'Maptastic' in 'CSL_Hamburg_Grasbrook/cityscope_grasbrook_angular/node_modules/maptastic/dist'
`

**Comment by andredaa** [comment]
> But it's coming from npm, not git. We don't commit any maptastic files.

yes exactly. ---> these changes probably would not survive a "npm install" if installed on a new machine. I emailed the package maintainers.

**Comment by RELNO** [comment]
I cannot test it on linux for now, but in any case the lib is not an npm lib. It's not maintain +5yrs. 
I've modified the original https://github.com/glowbox/maptasticjs to allow ES6 modules injections.

**Comment by andredaa** [comment]
> I've modified the original https://github.com/glowbox/maptasticjs to allow ES6 modules injections.
There's an npm clone also, but I never tested it: https://www.npmjs.com/package/maptastic

 In the[ package-lock.json](https://github.com/CityScope/CSL_Hamburg_Grasbrook/blob/30a0a30bf7a35618a273ebcaacc6479f3577b813/cityscope_grasbrook_angular/package-lock.json#L7499) it looks like it Maptastic is loaded via npm. 
Source: https://github.com/austince/maptasticjs -> he emailed to me that he would be happy to incorporate a fix.

Where is the source to your modified version? And how is it integrated into this repo?

**Comment by luftj** [comment]
https://github.com/CityScope/CSL_Hamburg_Grasbrook/commit/0f9ce365d5e8f5ed053fb9d0c129b84262baa1d2 changes the dependancy temporarily to my fork of the module: https://github.com/luftj/maptasticjs

**Comment by luftj** [comment]
maptastic removed from UI for now 363f88bf82aab2273b60cef8ae9dcfad3f03049c
