### ISSUE TITLE
works without save-dev package

### ISSUE THREAD

**Issue by yasushisakai** [CityScope/CSL_Hamburg_Grasbrook#75]
while trying to run the angular app it in my local environment, `npm install` stopped because of a 404 NOT FOUND error for this `save-dev` package.

https://github.com/CityScope/CSL_Hamburg_Grasbrook/blob/68f27517467510ed304f262d75246f2b05b799c4/cityscope_grasbrook_angular/package.json#L32

after I snip this off, the install process and the `ng serve` went through without any complaints.

**Comment by RELNO** [comment]
Has the same issue after clean install, save-dev is not found

**Comment by RELNO** [comment]
I think it's solved with current `package.json`. closing .
