### ISSUE TITLE
Clearer UI for land-use parent classes 

### ISSUE THREAD

**Issue by RELNO** [CityScope/CSL_Hamburg_Grasbrook#85]
When selecting grid cells, the pop-up menu shows all major design classes (building, street, open space): 

<img width="524" alt="Screen Shot 2019-11-29 at 10 36 28" src="https://user-images.githubusercontent.com/14296774/69878905-1ed5a880-1294-11ea-9ddd-5d67284ece34.png">

I find it a bit confusing since users might assume it's a 'and' not 'or' selection, meaning users can edit both building AND landscape features of a cell (which is theoretically possible). 
For simplicity I'd suggest to have kind of top-level slider/toggle/button to select the three parent classes, and then show the specific settings.

**Comment by illsio** [comment]
Maybe a clearer indication of what is selected would also solve the issue?

**Comment by RELNO** [comment]
possible, how'd you show that?

**Comment by RELNO** [comment]
Imagined something along these lines (might need text as well)
<img width="382" alt="Screen Shot 2019-11-29 at 14 30 49" src="https://user-images.githubusercontent.com/14296774/69887436-e85c5580-12b4-11ea-89e3-247ea813a88b.png">

**Comment by illsio** [comment]
is this how you imagined it?

**Comment by RELNO** [comment]
looks great, thanks. Text for parent labels? What do you think?
