### ISSUE TITLE
modules do not update after first time 'save'

### ISSUE THREAD

**Issue by RELNO** [CityScope/CSL_Hamburg_Grasbrook#87]
During the meeting y-day we tried to change a design and see module reaction. This worked on the first 'save' but not on the second time.

**Comment by luftj** [comment]
can't reproduce. I can arbitrarily often change the grid, submit it and get new results for all running modules.

**Comment by RELNO** [comment]
Might be that noise module is off, but on test now spinner goes forever with no update.

**Comment by luftj** [comment]
modules broke due to cityIO outage. will work on robustness
