### ISSUE TITLE
'save' UI should be amended to compute or analyze. 

### ISSUE THREAD

**Issue by RELNO** [CityScope/CSL_Hamburg_Grasbrook#88]
Might be also good to move all buttons to right side and make room for legends

**Comment by RELNO** [comment]
@illsio thanks, saw the latest update and it look much better. One last comment on this is to consider shifting all view control buttons as well to the right side UI so legend are not overlapping

**Comment by illsio** [comment]
are they still overlapping ATM? 
only in possible cases of very large legends right?

**Comment by RELNO** [comment]
It's sort of overlapping on large legend, but will fully overlap on smaller resolution than retina

**Comment by luftj** [comment]
additional height-dependance to go absolutely sure for weird aspect ratios
