### ISSUE TITLE
CS table extents -- please review 

### ISSUE THREAD

**Issue by RELNO** [CityScope/CSL_Hamburg_Grasbrook#9]
@LAAP, Markus and I are closing in on the extents of the physical table and we'd like to see if there's any input.
![CityScope GB](https://user-images.githubusercontent.com/14296774/55885641-50202d80-5b78-11e9-842c-5fd40a9f88fc.jpg)

To keep this repo clean, here's the GIS files: https://drive.google.com/drive/folders/146FUOk_JaN9Rnnypkh9kZNQlHOcofZxK?usp=sharing
In Qgis, go to Layouts and select `cityscope gb`

**Comment by agrignard** [comment]
What was discussed in one of the meeting was to slightly translate the grid to the top so that the edge (the orange line on this picture) was in the middle of the water. I don't know what we decided at the end

**Comment by RELNO** [comment]
@agrignard thanks -- here's another options that has 'cleaner' plates 
<img width="827" alt="Screen Shot 2019-04-10 at 11 20 43" src="https://user-images.githubusercontent.com/14296774/55891618-dfcad980-5b82-11e9-8efa-435b04bb920d.png">

**Comment by RELNO** [comment]
this one is a bit better in terms of exposing the south part of the site and also makes the north part closter to people interacting

**Comment by doorleyr** [comment]
Which plates would be interactive zone?

**Comment by RELNO** [comment]
Not yet decided -- Kent has some input on this, we'll know more later. For now we can assume most non water area is active, though most of it might be static

**Comment by LAAP** [comment]
I think that plates are not longer relevant. Since Chinese plates are 50x50, and we have a mix of LEGO and Chinese plates... We should focus on other way of measuring

**Comment by RELNO** [comment]
version based on current table dimensions: 
![CS_GB](https://user-images.githubusercontent.com/14296774/56065187-261a6700-5d42-11e9-8002-12bf223c67ce.jpg)

**Comment by RELNO** [comment]
@agrignard rotation @144 deg, zoom in to see VOXEL™ parallelism:
 
![CityScope Table](https://user-images.githubusercontent.com/14296774/56073358-609af880-5d70-11e9-9f4b-53a3decb8e1e.jpg)

**Comment by agrignard** [comment]
What about having a ```data```folder in the github with the table boundaries?

**Comment by RELNO** [comment]
@agrignard sure. What would you see as the best way to convert https://github.com/CityScope/CSL_Hamburg_Grasbrook/issues/9#issuecomment-482768158 to let long?

**Comment by agrignard** [comment]
Ideally having a .shp file correctly projected which is only a rectangle representing the boundary of the table like here 
https://github.com/CityScope/CS_Simulation_GAMA/blob/master/CS_CityScope_GAMA/includes/City/volpe/table_bounds.shp

Less ideally having at least the 4 corner lat and long value 

Right now I cannot open the shapefile in 
https://drive.google.com/drive/folders/146FUOk_JaN9Rnnypkh9kZNQlHOcofZxK?usp=sharing

**Comment by RELNO** [comment]
@agrignard it was an empty shp file. I've removed all but the qgis project. For the extents In Qgis layout, go to Layouts and select `cityscope gb`

**Comment by agrignard** [comment]
can you save it as a .qgs? .qgz is a new for mat only available in the latest QGIS version

**Comment by RELNO** [comment]
done, LMK if not working

**Comment by RELNO** [comment]
![CityScope Table](https://user-images.githubusercontent.com/14296774/56443064-f37fe980-62c0-11e9-87f1-b92a9b0a3cdc.jpg)
checkup with web mercator

**Comment by agrignard** [comment]
Any chance to have the .geosjon and/or .shp of the table extends?  That would be very useful (not to say essential) for any potential backEnd applications

**Comment by RELNO** [comment]
map extents in lat long:
[10.00677491086256, 53.53789434597681],
    [10.02223991398489, 53.531586825893925],
    [10.016245501014993, 53.52640987365575],
    [10.000748807171703, 53.53278372885845],

**Comment by RELNO** [comment]
note to self: https://github.com/CityScope/CSL_Hamburg_Grasbrook/issues/9#issuecomment-485286858 to be stored in new version of cityIO API as a stand alnoe field, e.g `...grasbrook/table_extents` which will return a minimal Geojson: 
```
{
   "type": "Polygon",
   "coordinates": [
       [[10.00677491086256, 53.53789434597681],[10.02223991398489, 53.531586825893925],[10.016245501014993, 53.52640987365575],[10.000748807171703, 53.53278372885845],[10.00677491086256, 53.53789434597681]]
   ]
}
```
